name: elixir

on:
  push:
  pull_request:

jobs:
  test:
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - otp: '27'
          elixir: '1.17.3'
        - otp: '27'
          elixir: '1.18.4'
        - otp: '28'
          elixir: '1.19.5'
        - otp: '28'
          elixir: '1.20.0'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
